spring.application.name=med-app
spring.mongodb.uri= ${MONGO_URI}
logging.level.org.springframework.data.mongocdb.core=debug
spring.ai.google.genai.api-key= ${GOOGLE_API_KEY}
spring.ai.google.genai.chat.model= gemini-3.1-flash-lite

#email notification
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= ${MUSER_NAME}
spring.mail.password= ${PASS_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.required=true

#razorpay
razorpay.key_id= ${RAZORPAY_KEY_ID}
razorpay.key_secret= ${RAZORPAY_KEY_SECRET}

#Intial Users
app.security.admin.username=${ADMIN_USERNAME}
app.security.admin.password=${ADMIN_PASSWORD}

app.security.patient.username=${PATIENT_USERNAME}
app.security.patient.password=${PATIENT_PASSWORD}

app.security.doctor.username=${DOCTOR_USERNAME}
app.security.doctor.password=${DOCTOR_PASSWORD}

app.security.pharmacist.username=${PHARMACIST_USERNAME}
app.security.pharmacist.password=${PHARMACIST_PASSWORD}





