spring.application.name=med-app
spring.mongodb.uri= ${MONGO_URI}
logging.level.org.springframework.data.mongocdb.core=debug

#email notification
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= ${MUSER_NAME}
spring.mail.password= ${PASS_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.required=true

#razorpay
razorpay.key_id= ${RAZORPAY_KEY_ID}
razorpay.key_secret= ${RAZORPAY_KEY_SECRET}